-- CreateTable
CREATE TABLE `CatalogTag` (
    `id` VARCHAR(191) NOT NULL,
    `group` ENUM('subjects', 'settings', 'backgrounds', 'roles', 'tones', 'audiences') NOT NULL,
    `name` VARCHAR(32) NOT NULL,
    `status` ENUM('ACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
    `sortOrder` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `CatalogTag_group_name_key`(`group`, `name`),
    INDEX `CatalogTag_status_group_sortOrder_idx`(`status`, `group`, `sortOrder`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO `CatalogTag` (`id`, `group`, `name`, `status`, `sortOrder`, `createdAt`, `updatedAt`) VALUES
('ctag_001', 'subjects', '现代', 'ACTIVE', 0, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_002', 'subjects', '女性成长', 'ACTIVE', 1, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_003', 'subjects', '脑洞', 'ACTIVE', 2, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_004', 'subjects', '奇幻', 'ACTIVE', 3, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_005', 'subjects', '玄幻', 'ACTIVE', 4, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_006', 'subjects', '古言', 'ACTIVE', 5, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_007', 'subjects', '战神', 'ACTIVE', 6, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_008', 'subjects', '宫斗', 'ACTIVE', 7, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_009', 'subjects', '仙侠', 'ACTIVE', 8, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_010', 'subjects', '权谋', 'ACTIVE', 9, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_011', 'subjects', '悬疑', 'ACTIVE', 10, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_012', 'subjects', '喜剧', 'ACTIVE', 11, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_013', 'subjects', '青春', 'ACTIVE', 12, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_014', 'subjects', '甜宠', 'ACTIVE', 13, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_015', 'subjects', '虐恋', 'ACTIVE', 14, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_016', 'subjects', '逆袭', 'ACTIVE', 15, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_017', 'subjects', '复仇', 'ACTIVE', 16, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_018', 'subjects', '萌宝', 'ACTIVE', 17, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_019', 'subjects', '赘婿', 'ACTIVE', 18, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_020', 'subjects', '神医', 'ACTIVE', 19, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_021', 'subjects', '兵王', 'ACTIVE', 20, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_022', 'settings', '打脸虐渣', 'ACTIVE', 100, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_023', 'settings', '大男主', 'ACTIVE', 101, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_024', 'settings', '大女主', 'ACTIVE', 102, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_025', 'settings', '马甲', 'ACTIVE', 103, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_026', 'settings', '重生', 'ACTIVE', 104, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_027', 'settings', '穿越', 'ACTIVE', 105, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_028', 'settings', '系统', 'ACTIVE', 106, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_029', 'settings', '先婚后爱', 'ACTIVE', 107, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_030', 'settings', '家长里短', 'ACTIVE', 108, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_031', 'settings', '破镜重圆', 'ACTIVE', 109, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_032', 'settings', '神豪', 'ACTIVE', 110, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_033', 'settings', '豪门', 'ACTIVE', 111, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_034', 'settings', '强者回归', 'ACTIVE', 112, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_035', 'settings', '异能', 'ACTIVE', 113, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_036', 'settings', '契约婚姻', 'ACTIVE', 114, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_037', 'settings', '替身', 'ACTIVE', 115, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_038', 'settings', '失忆', 'ACTIVE', 116, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_039', 'settings', '双洁', 'ACTIVE', 117, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_040', 'settings', '追妻火葬场', 'ACTIVE', 118, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_041', 'backgrounds', '现代', 'ACTIVE', 200, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_042', 'backgrounds', '都市', 'ACTIVE', 201, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_043', 'backgrounds', '古代', 'ACTIVE', 202, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_044', 'backgrounds', '乡村', 'ACTIVE', 203, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_045', 'backgrounds', '年代', 'ACTIVE', 204, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_046', 'backgrounds', '架空', 'ACTIVE', 205, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_047', 'backgrounds', '职场', 'ACTIVE', 206, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_048', 'backgrounds', '民国', 'ACTIVE', 207, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_049', 'backgrounds', '校园', 'ACTIVE', 208, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_050', 'backgrounds', '宫廷', 'ACTIVE', 209, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_051', 'roles', '总裁', 'ACTIVE', 300, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_052', 'roles', '女强', 'ACTIVE', 301, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_053', 'roles', '大叔', 'ACTIVE', 302, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_054', 'roles', '少年', 'ACTIVE', 303, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_055', 'roles', '反派', 'ACTIVE', 304, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_056', 'roles', '团宠', 'ACTIVE', 305, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_057', 'roles', '女配逆袭', 'ACTIVE', 306, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_058', 'tones', '轻松', 'ACTIVE', 400, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_059', 'tones', '高能', 'ACTIVE', 401, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_060', 'tones', '致郁', 'ACTIVE', 402, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_061', 'tones', '甜虐', 'ACTIVE', 403, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_062', 'tones', '搞笑', 'ACTIVE', 404, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_063', 'tones', '燃', 'ACTIVE', 405, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_064', 'audiences', '男频', 'ACTIVE', 500, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3)),
('ctag_065', 'audiences', '女频', 'ACTIVE', 501, CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));
